/*
 * WordpressV2API.PCL
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 03/06/2017
 */
using System;
using System.Linq;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using WordpressV2API.PCL;
using WordpressV2API.PCL.Utilities;

namespace WordpressV2API.PCL.Models
{
    [JsonConverter(typeof(StringValuedEnumConverter))]
    public enum CommentStatus34Enum
    {
        OPEN, //TODO: Write general description for this method
        CLOSED, //TODO: Write general description for this method
    }

    /// <summary>
    /// Helper for the enum type CommentStatus34Enum
    /// </summary>
    public static class CommentStatus34EnumHelper
    {
        //string values corresponding the enum elements
        private static List<string> stringValues = new List<string> { "open", "closed" };

        /// <summary>
        /// Converts a CommentStatus34Enum value to a corresponding string value
        /// </summary>
        /// <param name="enumValue">The CommentStatus34Enum value to convert</param>
        /// <returns>The representative string value</returns>
        public static string ToValue(CommentStatus34Enum enumValue)
        {
            switch(enumValue)
            {
                //only valid enum elements can be used
                //this is necessary to avoid errors
                case CommentStatus34Enum.OPEN:
                case CommentStatus34Enum.CLOSED:
                    return stringValues[(int)enumValue];

                //an invalid enum value was requested
                default:
                    return null;
            }
        }

        /// <summary>
        /// Convert a list of CommentStatus34Enum values to a list of strings
        /// </summary>
        /// <param name="enumValues">The list of CommentStatus34Enum values to convert</param>
        /// <returns>The list of representative string values</returns>
        public static List<string> ToValue(List<CommentStatus34Enum> enumValues)
        {
            if (null == enumValues)
                return null;

            return enumValues.Select(eVal => ToValue(eVal)).ToList();
        }

        /// <summary>
        /// Converts a string value into CommentStatus34Enum value
        /// </summary>
        /// <param name="value">The string value to parse</param>
        /// <returns>The parsed CommentStatus34Enum value</returns>
        public static CommentStatus34Enum ParseString(string value)
        {
            int index = stringValues.IndexOf(value);
            if(index < 0)
                throw new InvalidCastException(string.Format("Unable to cast value: {0} to type CommentStatus34Enum", value));

            return (CommentStatus34Enum) index;
        }
    }
} 