/*
 * WordpressV2API.PCL
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using WordpressV2API.PCL;
using WordpressV2API.PCL.Utilities;

namespace WordpressV2API.PCL.Models
{
    public class Comment : BaseModel 
    {
        // These fields hold the values for the public properties.
        private int? id;
        private string author;
        private string authorEmail;
        private string authorIp;
        private string authorName;
        private string authorUrl;
        private string authorUserAgent;
        private string content;
        private DateTime? date;
        private DateTime? dateGmt;
        private string karma;
        private string link;
        private int? parent;
        private string post;
        private Models.StatusEnum? status;
        private string type;
        private string authorAvatarUrls;

        /// <summary>
        /// Unique identifier for the object.
        /// </summary>
        [JsonProperty("id")]
        public int? Id 
        { 
            get 
            {
                return this.id; 
            } 
            set 
            {
                this.id = value;
                onPropertyChanged("Id");
            }
        }

        /// <summary>
        /// The id for the author of the object.
        /// </summary>
        [JsonProperty("author")]
        public string Author 
        { 
            get 
            {
                return this.author; 
            } 
            set 
            {
                this.author = value;
                onPropertyChanged("Author");
            }
        }

        /// <summary>
        /// Email address for the object author.
        /// </summary>
        [JsonProperty("author_email")]
        public string AuthorEmail 
        { 
            get 
            {
                return this.authorEmail; 
            } 
            set 
            {
                this.authorEmail = value;
                onPropertyChanged("AuthorEmail");
            }
        }

        /// <summary>
        /// IP address for the object author.
        /// </summary>
        [JsonProperty("author_ip")]
        public string AuthorIp 
        { 
            get 
            {
                return this.authorIp; 
            } 
            set 
            {
                this.authorIp = value;
                onPropertyChanged("AuthorIp");
            }
        }

        /// <summary>
        /// Display name for the object author.
        /// </summary>
        [JsonProperty("author_name")]
        public string AuthorName 
        { 
            get 
            {
                return this.authorName; 
            } 
            set 
            {
                this.authorName = value;
                onPropertyChanged("AuthorName");
            }
        }

        /// <summary>
        /// URL for the object author.
        /// </summary>
        [JsonProperty("author_url")]
        public string AuthorUrl 
        { 
            get 
            {
                return this.authorUrl; 
            } 
            set 
            {
                this.authorUrl = value;
                onPropertyChanged("AuthorUrl");
            }
        }

        /// <summary>
        /// User agent for the object author.
        /// </summary>
        [JsonProperty("author_user_agent")]
        public string AuthorUserAgent 
        { 
            get 
            {
                return this.authorUserAgent; 
            } 
            set 
            {
                this.authorUserAgent = value;
                onPropertyChanged("AuthorUserAgent");
            }
        }

        /// <summary>
        /// The content for the object.
        /// </summary>
        [JsonProperty("content")]
        public string Content 
        { 
            get 
            {
                return this.content; 
            } 
            set 
            {
                this.content = value;
                onPropertyChanged("Content");
            }
        }

        /// <summary>
        /// The date the object was published, in the site's timezone.
        /// </summary>
        [JsonConverter(typeof(IsoDateTimeConverter))]
        [JsonProperty("date")]
        public DateTime? Date 
        { 
            get 
            {
                return this.date; 
            } 
            set 
            {
                this.date = value;
                onPropertyChanged("Date");
            }
        }

        /// <summary>
        /// The date the object was published, as GMT.
        /// </summary>
        [JsonConverter(typeof(IsoDateTimeConverter))]
        [JsonProperty("date_gmt")]
        public DateTime? DateGmt 
        { 
            get 
            {
                return this.dateGmt; 
            } 
            set 
            {
                this.dateGmt = value;
                onPropertyChanged("DateGmt");
            }
        }

        /// <summary>
        /// Karma for the object
        /// </summary>
        [JsonProperty("karma")]
        public string Karma 
        { 
            get 
            {
                return this.karma; 
            } 
            set 
            {
                this.karma = value;
                onPropertyChanged("Karma");
            }
        }

        /// <summary>
        /// URL to the object.
        /// </summary>
        [JsonProperty("link")]
        public string Link 
        { 
            get 
            {
                return this.link; 
            } 
            set 
            {
                this.link = value;
                onPropertyChanged("Link");
            }
        }

        /// <summary>
        /// The id for the parent of the object.
        /// </summary>
        [JsonProperty("parent")]
        public int? Parent 
        { 
            get 
            {
                return this.parent; 
            } 
            set 
            {
                this.parent = value;
                onPropertyChanged("Parent");
            }
        }

        /// <summary>
        /// The id for the associated post of the resource.
        /// </summary>
        [JsonProperty("post")]
        public string Post 
        { 
            get 
            {
                return this.post; 
            } 
            set 
            {
                this.post = value;
                onPropertyChanged("Post");
            }
        }

        /// <summary>
        /// A named status for the object.
        /// </summary>
        [JsonProperty("status", ItemConverterType = typeof(StringValuedEnumConverter))]
        public Models.StatusEnum? Status 
        { 
            get 
            {
                return this.status; 
            } 
            set 
            {
                this.status = value;
                onPropertyChanged("Status");
            }
        }

        /// <summary>
        /// Type of Post for the object.
        /// </summary>
        [JsonProperty("type")]
        public string Type 
        { 
            get 
            {
                return this.type; 
            } 
            set 
            {
                this.type = value;
                onPropertyChanged("Type");
            }
        }

        /// <summary>
        /// Avatar URLs for the object author.
        /// </summary>
        [JsonProperty("author_avatar_urls")]
        public string AuthorAvatarUrls 
        { 
            get 
            {
                return this.authorAvatarUrls; 
            } 
            set 
            {
                this.authorAvatarUrls = value;
                onPropertyChanged("AuthorAvatarUrls");
            }
        }
    }
} 