/*
 * WordpressV2API.PCL
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 03/06/2017
 */
using System;
using System.Linq;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using WordpressV2API.PCL;
using WordpressV2API.PCL.Utilities;

namespace WordpressV2API.PCL.Models
{
    [JsonConverter(typeof(StringValuedEnumConverter))]
    public enum FormatEnum
    {
        STANDARD, //TODO: Write general description for this method
        ASIDE, //TODO: Write general description for this method
        CHAT, //TODO: Write general description for this method
        GALLERY, //TODO: Write general description for this method
        LINK, //TODO: Write general description for this method
        IMAGE, //TODO: Write general description for this method
        QUOTE, //TODO: Write general description for this method
        STATUS, //TODO: Write general description for this method
        VIDEO, //TODO: Write general description for this method
        AUDIO, //TODO: Write general description for this method
    }

    /// <summary>
    /// Helper for the enum type FormatEnum
    /// </summary>
    public static class FormatEnumHelper
    {
        //string values corresponding the enum elements
        private static List<string> stringValues = new List<string> { "standard", "aside", "chat", "gallery", "link", "image", "quote", "status", "video", "audio" };

        /// <summary>
        /// Converts a FormatEnum value to a corresponding string value
        /// </summary>
        /// <param name="enumValue">The FormatEnum value to convert</param>
        /// <returns>The representative string value</returns>
        public static string ToValue(FormatEnum enumValue)
        {
            switch(enumValue)
            {
                //only valid enum elements can be used
                //this is necessary to avoid errors
                case FormatEnum.STANDARD:
                case FormatEnum.ASIDE:
                case FormatEnum.CHAT:
                case FormatEnum.GALLERY:
                case FormatEnum.LINK:
                case FormatEnum.IMAGE:
                case FormatEnum.QUOTE:
                case FormatEnum.STATUS:
                case FormatEnum.VIDEO:
                case FormatEnum.AUDIO:
                    return stringValues[(int)enumValue];

                //an invalid enum value was requested
                default:
                    return null;
            }
        }

        /// <summary>
        /// Convert a list of FormatEnum values to a list of strings
        /// </summary>
        /// <param name="enumValues">The list of FormatEnum values to convert</param>
        /// <returns>The list of representative string values</returns>
        public static List<string> ToValue(List<FormatEnum> enumValues)
        {
            if (null == enumValues)
                return null;

            return enumValues.Select(eVal => ToValue(eVal)).ToList();
        }

        /// <summary>
        /// Converts a string value into FormatEnum value
        /// </summary>
        /// <param name="value">The string value to parse</param>
        /// <returns>The parsed FormatEnum value</returns>
        public static FormatEnum ParseString(string value)
        {
            int index = stringValues.IndexOf(value);
            if(index < 0)
                throw new InvalidCastException(string.Format("Unable to cast value: {0} to type FormatEnum", value));

            return (FormatEnum) index;
        }
    }
} 