/*
 * WordpressV2API.PCL
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 03/06/2017
 */
using System;
using System.Linq;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using WordpressV2API.PCL;
using WordpressV2API.PCL.Utilities;

namespace WordpressV2API.PCL.Models
{
    [JsonConverter(typeof(StringValuedEnumConverter))]
    public enum MediaTypeEnum
    {
        IMAGE, //TODO: Write general description for this method
        FILE, //TODO: Write general description for this method
    }

    /// <summary>
    /// Helper for the enum type MediaTypeEnum
    /// </summary>
    public static class MediaTypeEnumHelper
    {
        //string values corresponding the enum elements
        private static List<string> stringValues = new List<string> { "image", "file" };

        /// <summary>
        /// Converts a MediaTypeEnum value to a corresponding string value
        /// </summary>
        /// <param name="enumValue">The MediaTypeEnum value to convert</param>
        /// <returns>The representative string value</returns>
        public static string ToValue(MediaTypeEnum enumValue)
        {
            switch(enumValue)
            {
                //only valid enum elements can be used
                //this is necessary to avoid errors
                case MediaTypeEnum.IMAGE:
                case MediaTypeEnum.FILE:
                    return stringValues[(int)enumValue];

                //an invalid enum value was requested
                default:
                    return null;
            }
        }

        /// <summary>
        /// Convert a list of MediaTypeEnum values to a list of strings
        /// </summary>
        /// <param name="enumValues">The list of MediaTypeEnum values to convert</param>
        /// <returns>The list of representative string values</returns>
        public static List<string> ToValue(List<MediaTypeEnum> enumValues)
        {
            if (null == enumValues)
                return null;

            return enumValues.Select(eVal => ToValue(eVal)).ToList();
        }

        /// <summary>
        /// Converts a string value into MediaTypeEnum value
        /// </summary>
        /// <param name="value">The string value to parse</param>
        /// <returns>The parsed MediaTypeEnum value</returns>
        public static MediaTypeEnum ParseString(string value)
        {
            int index = stringValues.IndexOf(value);
            if(index < 0)
                throw new InvalidCastException(string.Format("Unable to cast value: {0} to type MediaTypeEnum", value));

            return (MediaTypeEnum) index;
        }
    }
} 