/*
 * WordpressV2API.PCL
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using WordpressV2API.PCL;
using WordpressV2API.PCL.Utilities;

namespace WordpressV2API.PCL.Models
{
    public class Media : BaseModel 
    {
        // These fields hold the values for the public properties.
        private DateTime? date;
        private DateTime? dateGmt;
        private string guid;
        private int? id;
        private DateTime? modified;
        private DateTime? modifiedGmt;
        private string password;
        private string slug;
        private Models.StatusEnum? status;
        private string type;
        private string title;
        private string author;
        private Models.CommentStatusEnum? commentStatus;
        private Models.PingStatusEnum? pingStatus;
        private string altText;
        private string caption;
        private string description;
        private Models.MediaTypeEnum? mediaType;
        private string mimeType;
        private string mediaDetails;
        private string post;
        private string sourceUrl;

        /// <summary>
        /// The date the object was published, in the site's timezone.
        /// </summary>
        [JsonConverter(typeof(IsoDateTimeConverter))]
        [JsonProperty("date")]
        public DateTime? Date 
        { 
            get 
            {
                return this.date; 
            } 
            set 
            {
                this.date = value;
                onPropertyChanged("Date");
            }
        }

        /// <summary>
        /// The date the object was published, as GMT.
        /// </summary>
        [JsonConverter(typeof(IsoDateTimeConverter))]
        [JsonProperty("date_gmt")]
        public DateTime? DateGmt 
        { 
            get 
            {
                return this.dateGmt; 
            } 
            set 
            {
                this.dateGmt = value;
                onPropertyChanged("DateGmt");
            }
        }

        /// <summary>
        /// The globally unique identifier for the object.
        /// </summary>
        [JsonProperty("guid")]
        public string Guid 
        { 
            get 
            {
                return this.guid; 
            } 
            set 
            {
                this.guid = value;
                onPropertyChanged("Guid");
            }
        }

        /// <summary>
        /// Unique identifier for the object.
        /// </summary>
        [JsonProperty("id")]
        public int? Id 
        { 
            get 
            {
                return this.id; 
            } 
            set 
            {
                this.id = value;
                onPropertyChanged("Id");
            }
        }

        /// <summary>
        /// The date the object was last modified, in the site's timezone.
        /// </summary>
        [JsonConverter(typeof(IsoDateTimeConverter))]
        [JsonProperty("modified")]
        public DateTime? Modified 
        { 
            get 
            {
                return this.modified; 
            } 
            set 
            {
                this.modified = value;
                onPropertyChanged("Modified");
            }
        }

        /// <summary>
        /// The date the object was last modified, as GMT.
        /// </summary>
        [JsonConverter(typeof(IsoDateTimeConverter))]
        [JsonProperty("modified_gmt")]
        public DateTime? ModifiedGmt 
        { 
            get 
            {
                return this.modifiedGmt; 
            } 
            set 
            {
                this.modifiedGmt = value;
                onPropertyChanged("ModifiedGmt");
            }
        }

        /// <summary>
        /// The A password to protect access to the post.
        /// </summary>
        [JsonProperty("password")]
        public string Password 
        { 
            get 
            {
                return this.password; 
            } 
            set 
            {
                this.password = value;
                onPropertyChanged("Password");
            }
        }

        /// <summary>
        /// An alphanumeric identifier for the object unique to its type.
        /// </summary>
        [JsonProperty("slug")]
        public string Slug 
        { 
            get 
            {
                return this.slug; 
            } 
            set 
            {
                this.slug = value;
                onPropertyChanged("Slug");
            }
        }

        /// <summary>
        /// A named status for the object.
        /// </summary>
        [JsonProperty("status", ItemConverterType = typeof(StringValuedEnumConverter))]
        public Models.StatusEnum? Status 
        { 
            get 
            {
                return this.status; 
            } 
            set 
            {
                this.status = value;
                onPropertyChanged("Status");
            }
        }

        /// <summary>
        /// Type of Post for the object.
        /// </summary>
        [JsonProperty("type")]
        public string Type 
        { 
            get 
            {
                return this.type; 
            } 
            set 
            {
                this.type = value;
                onPropertyChanged("Type");
            }
        }

        /// <summary>
        /// The title for the object.
        /// </summary>
        [JsonProperty("title")]
        public string Title 
        { 
            get 
            {
                return this.title; 
            } 
            set 
            {
                this.title = value;
                onPropertyChanged("Title");
            }
        }

        /// <summary>
        /// The id for the author of the object.
        /// </summary>
        [JsonProperty("author")]
        public string Author 
        { 
            get 
            {
                return this.author; 
            } 
            set 
            {
                this.author = value;
                onPropertyChanged("Author");
            }
        }

        /// <summary>
        /// Whether or not comments are open on the object
        /// </summary>
        [JsonProperty("comment_status", ItemConverterType = typeof(StringValuedEnumConverter))]
        public Models.CommentStatusEnum? CommentStatus 
        { 
            get 
            {
                return this.commentStatus; 
            } 
            set 
            {
                this.commentStatus = value;
                onPropertyChanged("CommentStatus");
            }
        }

        /// <summary>
        /// Whether or not the object can be pinged.
        /// </summary>
        [JsonProperty("ping_status", ItemConverterType = typeof(StringValuedEnumConverter))]
        public Models.PingStatusEnum? PingStatus 
        { 
            get 
            {
                return this.pingStatus; 
            } 
            set 
            {
                this.pingStatus = value;
                onPropertyChanged("PingStatus");
            }
        }

        /// <summary>
        /// Alternative text to display when resource is not displayed
        /// </summary>
        [JsonProperty("alt_text")]
        public string AltText 
        { 
            get 
            {
                return this.altText; 
            } 
            set 
            {
                this.altText = value;
                onPropertyChanged("AltText");
            }
        }

        /// <summary>
        /// The caption for the resource.
        /// </summary>
        [JsonProperty("caption")]
        public string Caption 
        { 
            get 
            {
                return this.caption; 
            } 
            set 
            {
                this.caption = value;
                onPropertyChanged("Caption");
            }
        }

        /// <summary>
        /// The description for the resource.
        /// </summary>
        [JsonProperty("description")]
        public string Description 
        { 
            get 
            {
                return this.description; 
            } 
            set 
            {
                this.description = value;
                onPropertyChanged("Description");
            }
        }

        /// <summary>
        /// Type of resource.
        /// </summary>
        [JsonProperty("media_type", ItemConverterType = typeof(StringValuedEnumConverter))]
        public Models.MediaTypeEnum? MediaType 
        { 
            get 
            {
                return this.mediaType; 
            } 
            set 
            {
                this.mediaType = value;
                onPropertyChanged("MediaType");
            }
        }

        /// <summary>
        /// Mime type of resource.
        /// </summary>
        [JsonProperty("mime_type")]
        public string MimeType 
        { 
            get 
            {
                return this.mimeType; 
            } 
            set 
            {
                this.mimeType = value;
                onPropertyChanged("MimeType");
            }
        }

        /// <summary>
        /// Details about the resource file, specific to its type.
        /// </summary>
        [JsonProperty("media_details")]
        public string MediaDetails 
        { 
            get 
            {
                return this.mediaDetails; 
            } 
            set 
            {
                this.mediaDetails = value;
                onPropertyChanged("MediaDetails");
            }
        }

        /// <summary>
        /// The id for the associated post of the resource.
        /// </summary>
        [JsonProperty("post")]
        public string Post 
        { 
            get 
            {
                return this.post; 
            } 
            set 
            {
                this.post = value;
                onPropertyChanged("Post");
            }
        }

        /// <summary>
        /// URL to the original resource file.
        /// </summary>
        [JsonProperty("source_url")]
        public string SourceUrl 
        { 
            get 
            {
                return this.sourceUrl; 
            } 
            set 
            {
                this.sourceUrl = value;
                onPropertyChanged("SourceUrl");
            }
        }
    }
} 