/*
 * WordpressV2API.PCL
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 03/06/2017
 */
using System;
using System.Linq;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using WordpressV2API.PCL;
using WordpressV2API.PCL.Utilities;

namespace WordpressV2API.PCL.Models
{
    [JsonConverter(typeof(StringValuedEnumConverter))]
    public enum OrderbyEnum
    {
        DATE, //TODO: Write general description for this method
        ID, //TODO: Write general description for this method
        INCLUDE, //TODO: Write general description for this method
        TITLE, //TODO: Write general description for this method
        SLUG, //TODO: Write general description for this method
    }

    /// <summary>
    /// Helper for the enum type OrderbyEnum
    /// </summary>
    public static class OrderbyEnumHelper
    {
        //string values corresponding the enum elements
        private static List<string> stringValues = new List<string> { "date", "id", "include", "title", "slug" };

        /// <summary>
        /// Converts a OrderbyEnum value to a corresponding string value
        /// </summary>
        /// <param name="enumValue">The OrderbyEnum value to convert</param>
        /// <returns>The representative string value</returns>
        public static string ToValue(OrderbyEnum enumValue)
        {
            switch(enumValue)
            {
                //only valid enum elements can be used
                //this is necessary to avoid errors
                case OrderbyEnum.DATE:
                case OrderbyEnum.ID:
                case OrderbyEnum.INCLUDE:
                case OrderbyEnum.TITLE:
                case OrderbyEnum.SLUG:
                    return stringValues[(int)enumValue];

                //an invalid enum value was requested
                default:
                    return null;
            }
        }

        /// <summary>
        /// Convert a list of OrderbyEnum values to a list of strings
        /// </summary>
        /// <param name="enumValues">The list of OrderbyEnum values to convert</param>
        /// <returns>The list of representative string values</returns>
        public static List<string> ToValue(List<OrderbyEnum> enumValues)
        {
            if (null == enumValues)
                return null;

            return enumValues.Select(eVal => ToValue(eVal)).ToList();
        }

        /// <summary>
        /// Converts a string value into OrderbyEnum value
        /// </summary>
        /// <param name="value">The string value to parse</param>
        /// <returns>The parsed OrderbyEnum value</returns>
        public static OrderbyEnum ParseString(string value)
        {
            int index = stringValues.IndexOf(value);
            if(index < 0)
                throw new InvalidCastException(string.Format("Unable to cast value: {0} to type OrderbyEnum", value));

            return (OrderbyEnum) index;
        }
    }
} 