/*
 * WordpressV2API.PCL
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using WordpressV2API.PCL;
using WordpressV2API.PCL.Utilities;

namespace WordpressV2API.PCL.Models
{
    public class Post : BaseModel 
    {
        // These fields hold the values for the public properties.
        private DateTime? date;
        private DateTime? dateGmt;
        private string guid;
        private int? id;
        private string link;
        private DateTime? modified;
        private DateTime? modifiedGmt;
        private string password;
        private string slug;
        private Models.StatusEnum? status;
        private string type;
        private string title;
        private string content;
        private string author;
        private string excerpt;
        private string featuredMedia;
        private Models.CommentStatusEnum? commentStatus;
        private Models.PingStatusEnum? pingStatus;
        private Models.FormatEnum? format;
        private bool? sticky;
        private List<string> categories;
        private List<string> tags;

        /// <summary>
        /// The date the object was published, in the site's timezone.
        /// </summary>
        [JsonConverter(typeof(IsoDateTimeConverter))]
        [JsonProperty("date")]
        public DateTime? Date 
        { 
            get 
            {
                return this.date; 
            } 
            set 
            {
                this.date = value;
                onPropertyChanged("Date");
            }
        }

        /// <summary>
        /// The date the object was published, as GMT.
        /// </summary>
        [JsonConverter(typeof(IsoDateTimeConverter))]
        [JsonProperty("date_gmt")]
        public DateTime? DateGmt 
        { 
            get 
            {
                return this.dateGmt; 
            } 
            set 
            {
                this.dateGmt = value;
                onPropertyChanged("DateGmt");
            }
        }

        /// <summary>
        /// The globally unique identifier for the object.
        /// </summary>
        [JsonProperty("guid")]
        public string Guid 
        { 
            get 
            {
                return this.guid; 
            } 
            set 
            {
                this.guid = value;
                onPropertyChanged("Guid");
            }
        }

        /// <summary>
        /// Unique identifier for the object.
        /// </summary>
        [JsonProperty("id")]
        public int? Id 
        { 
            get 
            {
                return this.id; 
            } 
            set 
            {
                this.id = value;
                onPropertyChanged("Id");
            }
        }

        /// <summary>
        /// URL to the object.
        /// </summary>
        [JsonProperty("link")]
        public string Link 
        { 
            get 
            {
                return this.link; 
            } 
            set 
            {
                this.link = value;
                onPropertyChanged("Link");
            }
        }

        /// <summary>
        /// The date the object was last modified, in the site's timezone.
        /// </summary>
        [JsonConverter(typeof(IsoDateTimeConverter))]
        [JsonProperty("modified")]
        public DateTime? Modified 
        { 
            get 
            {
                return this.modified; 
            } 
            set 
            {
                this.modified = value;
                onPropertyChanged("Modified");
            }
        }

        /// <summary>
        /// The date the object was last modified, as GMT.
        /// </summary>
        [JsonConverter(typeof(IsoDateTimeConverter))]
        [JsonProperty("modified_gmt")]
        public DateTime? ModifiedGmt 
        { 
            get 
            {
                return this.modifiedGmt; 
            } 
            set 
            {
                this.modifiedGmt = value;
                onPropertyChanged("ModifiedGmt");
            }
        }

        /// <summary>
        /// The A password to protect access to the post.
        /// </summary>
        [JsonProperty("password")]
        public string Password 
        { 
            get 
            {
                return this.password; 
            } 
            set 
            {
                this.password = value;
                onPropertyChanged("Password");
            }
        }

        /// <summary>
        /// An alphanumeric identifier for the object unique to its type.
        /// </summary>
        [JsonProperty("slug")]
        public string Slug 
        { 
            get 
            {
                return this.slug; 
            } 
            set 
            {
                this.slug = value;
                onPropertyChanged("Slug");
            }
        }

        /// <summary>
        /// A named status for the object.
        /// </summary>
        [JsonProperty("status", ItemConverterType = typeof(StringValuedEnumConverter))]
        public Models.StatusEnum? Status 
        { 
            get 
            {
                return this.status; 
            } 
            set 
            {
                this.status = value;
                onPropertyChanged("Status");
            }
        }

        /// <summary>
        /// Type of Post for the object.
        /// </summary>
        [JsonProperty("type")]
        public string Type 
        { 
            get 
            {
                return this.type; 
            } 
            set 
            {
                this.type = value;
                onPropertyChanged("Type");
            }
        }

        /// <summary>
        /// The title for the object.
        /// </summary>
        [JsonProperty("title")]
        public string Title 
        { 
            get 
            {
                return this.title; 
            } 
            set 
            {
                this.title = value;
                onPropertyChanged("Title");
            }
        }

        /// <summary>
        /// The content for the object.
        /// </summary>
        [JsonProperty("content")]
        public string Content 
        { 
            get 
            {
                return this.content; 
            } 
            set 
            {
                this.content = value;
                onPropertyChanged("Content");
            }
        }

        /// <summary>
        /// The id for the author of the object.
        /// </summary>
        [JsonProperty("author")]
        public string Author 
        { 
            get 
            {
                return this.author; 
            } 
            set 
            {
                this.author = value;
                onPropertyChanged("Author");
            }
        }

        /// <summary>
        /// The excerpt for the object
        /// </summary>
        [JsonProperty("excerpt")]
        public string Excerpt 
        { 
            get 
            {
                return this.excerpt; 
            } 
            set 
            {
                this.excerpt = value;
                onPropertyChanged("Excerpt");
            }
        }

        /// <summary>
        /// The id of the featured media for the object.
        /// </summary>
        [JsonProperty("featured_media")]
        public string FeaturedMedia 
        { 
            get 
            {
                return this.featuredMedia; 
            } 
            set 
            {
                this.featuredMedia = value;
                onPropertyChanged("FeaturedMedia");
            }
        }

        /// <summary>
        /// Whether or not comments are open on the object
        /// </summary>
        [JsonProperty("comment_status", ItemConverterType = typeof(StringValuedEnumConverter))]
        public Models.CommentStatusEnum? CommentStatus 
        { 
            get 
            {
                return this.commentStatus; 
            } 
            set 
            {
                this.commentStatus = value;
                onPropertyChanged("CommentStatus");
            }
        }

        /// <summary>
        /// Whether or not the object can be pinged.
        /// </summary>
        [JsonProperty("ping_status", ItemConverterType = typeof(StringValuedEnumConverter))]
        public Models.PingStatusEnum? PingStatus 
        { 
            get 
            {
                return this.pingStatus; 
            } 
            set 
            {
                this.pingStatus = value;
                onPropertyChanged("PingStatus");
            }
        }

        /// <summary>
        /// The format for the object.
        /// </summary>
        [JsonProperty("format", ItemConverterType = typeof(StringValuedEnumConverter))]
        public Models.FormatEnum? Format 
        { 
            get 
            {
                return this.format; 
            } 
            set 
            {
                this.format = value;
                onPropertyChanged("Format");
            }
        }

        /// <summary>
        /// Whether or not the object should be treated as sticky.
        /// </summary>
        [JsonProperty("sticky")]
        public bool? Sticky 
        { 
            get 
            {
                return this.sticky; 
            } 
            set 
            {
                this.sticky = value;
                onPropertyChanged("Sticky");
            }
        }

        /// <summary>
        /// The terms assigned to the object in the category taxonomy.
        /// </summary>
        [JsonProperty("categories")]
        public List<string> Categories 
        { 
            get 
            {
                return this.categories; 
            } 
            set 
            {
                this.categories = value;
                onPropertyChanged("Categories");
            }
        }

        /// <summary>
        /// he terms assigned to the object in the post_tag taxonomy.
        /// </summary>
        [JsonProperty("tags")]
        public List<string> Tags 
        { 
            get 
            {
                return this.tags; 
            } 
            set 
            {
                this.tags = value;
                onPropertyChanged("Tags");
            }
        }
    }
} 