/*
 * WordpressV2API.PCL
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using WordpressV2API.PCL;
using WordpressV2API.PCL.Utilities;

namespace WordpressV2API.PCL.Models
{
    public class Revision : BaseModel 
    {
        // These fields hold the values for the public properties.
        private DateTime? date;
        private DateTime? dateGmt;
        private string guid;
        private int? id;
        private DateTime? modified;
        private DateTime? modifiedGmt;
        private string slug;
        private string title;
        private string content;
        private string author;
        private string excerpt;
        private int? parent;

        /// <summary>
        /// The date the object was published, in the site's timezone.
        /// </summary>
        [JsonConverter(typeof(IsoDateTimeConverter))]
        [JsonProperty("date")]
        public DateTime? Date 
        { 
            get 
            {
                return this.date; 
            } 
            set 
            {
                this.date = value;
                onPropertyChanged("Date");
            }
        }

        /// <summary>
        /// The date the object was published, as GMT.
        /// </summary>
        [JsonConverter(typeof(IsoDateTimeConverter))]
        [JsonProperty("date_gmt")]
        public DateTime? DateGmt 
        { 
            get 
            {
                return this.dateGmt; 
            } 
            set 
            {
                this.dateGmt = value;
                onPropertyChanged("DateGmt");
            }
        }

        /// <summary>
        /// The globally unique identifier for the object.
        /// </summary>
        [JsonProperty("guid")]
        public string Guid 
        { 
            get 
            {
                return this.guid; 
            } 
            set 
            {
                this.guid = value;
                onPropertyChanged("Guid");
            }
        }

        /// <summary>
        /// Unique identifier for the object.
        /// </summary>
        [JsonProperty("id")]
        public int? Id 
        { 
            get 
            {
                return this.id; 
            } 
            set 
            {
                this.id = value;
                onPropertyChanged("Id");
            }
        }

        /// <summary>
        /// The date the object was last modified, in the site's timezone.
        /// </summary>
        [JsonConverter(typeof(IsoDateTimeConverter))]
        [JsonProperty("modified")]
        public DateTime? Modified 
        { 
            get 
            {
                return this.modified; 
            } 
            set 
            {
                this.modified = value;
                onPropertyChanged("Modified");
            }
        }

        /// <summary>
        /// The date the object was last modified, as GMT.
        /// </summary>
        [JsonConverter(typeof(IsoDateTimeConverter))]
        [JsonProperty("modified_gmt")]
        public DateTime? ModifiedGmt 
        { 
            get 
            {
                return this.modifiedGmt; 
            } 
            set 
            {
                this.modifiedGmt = value;
                onPropertyChanged("ModifiedGmt");
            }
        }

        /// <summary>
        /// An alphanumeric identifier for the object unique to its type.
        /// </summary>
        [JsonProperty("slug")]
        public string Slug 
        { 
            get 
            {
                return this.slug; 
            } 
            set 
            {
                this.slug = value;
                onPropertyChanged("Slug");
            }
        }

        /// <summary>
        /// The title for the object.
        /// </summary>
        [JsonProperty("title")]
        public string Title 
        { 
            get 
            {
                return this.title; 
            } 
            set 
            {
                this.title = value;
                onPropertyChanged("Title");
            }
        }

        /// <summary>
        /// The content for the object.
        /// </summary>
        [JsonProperty("content")]
        public string Content 
        { 
            get 
            {
                return this.content; 
            } 
            set 
            {
                this.content = value;
                onPropertyChanged("Content");
            }
        }

        /// <summary>
        /// The id for the author of the object.
        /// </summary>
        [JsonProperty("author")]
        public string Author 
        { 
            get 
            {
                return this.author; 
            } 
            set 
            {
                this.author = value;
                onPropertyChanged("Author");
            }
        }

        /// <summary>
        /// The excerpt for the object
        /// </summary>
        [JsonProperty("excerpt")]
        public string Excerpt 
        { 
            get 
            {
                return this.excerpt; 
            } 
            set 
            {
                this.excerpt = value;
                onPropertyChanged("Excerpt");
            }
        }

        /// <summary>
        /// The id for the parent of the object.
        /// </summary>
        [JsonProperty("parent")]
        public int? Parent 
        { 
            get 
            {
                return this.parent; 
            } 
            set 
            {
                this.parent = value;
                onPropertyChanged("Parent");
            }
        }
    }
} 