/*
 * WordpressV2API.PCL
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using WordpressV2API.PCL;
using WordpressV2API.PCL.Utilities;

namespace WordpressV2API.PCL.Models
{
    public class Status3 : BaseModel 
    {
        // These fields hold the values for the public properties.
        private bool? mprivate;
        private bool? mprotected;
        private bool? mpublic;
        private bool? queryable;
        private bool? showInList;
        private string name;
        private string slug;

        /// <summary>
        /// Whether posts with this resource should be private.
        /// </summary>
        [JsonProperty("private")]
        public bool? Private 
        { 
            get 
            {
                return this.mprivate; 
            } 
            set 
            {
                this.mprivate = value;
                onPropertyChanged("Private");
            }
        }

        /// <summary>
        /// Whether posts with this resource should be protected.
        /// </summary>
        [JsonProperty("protected")]
        public bool? Protected 
        { 
            get 
            {
                return this.mprotected; 
            } 
            set 
            {
                this.mprotected = value;
                onPropertyChanged("Protected");
            }
        }

        /// <summary>
        /// Whether posts of this resource should be shown in the front end of the site.
        /// </summary>
        [JsonProperty("public")]
        public bool? Public 
        { 
            get 
            {
                return this.mpublic; 
            } 
            set 
            {
                this.mpublic = value;
                onPropertyChanged("Public");
            }
        }

        /// <summary>
        /// Whether posts with this resource should be publicly-queryable.
        /// </summary>
        [JsonProperty("queryable")]
        public bool? Queryable 
        { 
            get 
            {
                return this.queryable; 
            } 
            set 
            {
                this.queryable = value;
                onPropertyChanged("Queryable");
            }
        }

        /// <summary>
        /// Whether to include posts in the edit listing for their post type.
        /// </summary>
        [JsonProperty("show_in_list")]
        public bool? ShowInList 
        { 
            get 
            {
                return this.showInList; 
            } 
            set 
            {
                this.showInList = value;
                onPropertyChanged("ShowInList");
            }
        }

        /// <summary>
        /// The title for the resource.
        /// </summary>
        [JsonProperty("name")]
        public string Name 
        { 
            get 
            {
                return this.name; 
            } 
            set 
            {
                this.name = value;
                onPropertyChanged("Name");
            }
        }

        /// <summary>
        /// An alphanumeric identifier for the object unique to its type.
        /// </summary>
        [JsonProperty("slug")]
        public string Slug 
        { 
            get 
            {
                return this.slug; 
            } 
            set 
            {
                this.slug = value;
                onPropertyChanged("Slug");
            }
        }
    }
} 