/*
 * WordpressV2API.PCL
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using WordpressV2API.PCL;
using WordpressV2API.PCL.Utilities;

namespace WordpressV2API.PCL.Models
{
    public class Tag : BaseModel 
    {
        // These fields hold the values for the public properties.
        private int? id;
        private int? count;
        private string description;
        private string link;
        private string name;
        private string slug;
        private Models.Taxonomy6Enum? taxonomy;

        /// <summary>
        /// Unique identifier for the object.
        /// </summary>
        [JsonProperty("id")]
        public int? Id 
        { 
            get 
            {
                return this.id; 
            } 
            set 
            {
                this.id = value;
                onPropertyChanged("Id");
            }
        }

        /// <summary>
        /// Number of published posts for the resource.
        /// </summary>
        [JsonProperty("count")]
        public int? Count 
        { 
            get 
            {
                return this.count; 
            } 
            set 
            {
                this.count = value;
                onPropertyChanged("Count");
            }
        }

        /// <summary>
        /// The description for the resource.
        /// </summary>
        [JsonProperty("description")]
        public string Description 
        { 
            get 
            {
                return this.description; 
            } 
            set 
            {
                this.description = value;
                onPropertyChanged("Description");
            }
        }

        /// <summary>
        /// URL to the object.
        /// </summary>
        [JsonProperty("link")]
        public string Link 
        { 
            get 
            {
                return this.link; 
            } 
            set 
            {
                this.link = value;
                onPropertyChanged("Link");
            }
        }

        /// <summary>
        /// The title for the resource.
        /// </summary>
        [JsonProperty("name")]
        public string Name 
        { 
            get 
            {
                return this.name; 
            } 
            set 
            {
                this.name = value;
                onPropertyChanged("Name");
            }
        }

        /// <summary>
        /// An alphanumeric identifier for the object unique to its type.
        /// </summary>
        [JsonProperty("slug")]
        public string Slug 
        { 
            get 
            {
                return this.slug; 
            } 
            set 
            {
                this.slug = value;
                onPropertyChanged("Slug");
            }
        }

        /// <summary>
        /// Type attribution for the resource.
        /// </summary>
        [JsonProperty("taxonomy", ItemConverterType = typeof(StringValuedEnumConverter))]
        public Models.Taxonomy6Enum? Taxonomy 
        { 
            get 
            {
                return this.taxonomy; 
            } 
            set 
            {
                this.taxonomy = value;
                onPropertyChanged("Taxonomy");
            }
        }
    }
} 