/*
 * WordpressV2API.PCL
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using WordpressV2API.PCL;
using WordpressV2API.PCL.Utilities;

namespace WordpressV2API.PCL.Models
{
    public class Taxonomy : BaseModel 
    {
        // These fields hold the values for the public properties.
        private List<string> capabilities;
        private string description;
        private string hierarchical;
        private string labels;
        private string name;
        private string slug;
        private bool? showCloud;
        private List<string> types;

        /// <summary>
        /// All capabilities used by the resource.
        /// </summary>
        [JsonProperty("capabilities")]
        public List<string> Capabilities 
        { 
            get 
            {
                return this.capabilities; 
            } 
            set 
            {
                this.capabilities = value;
                onPropertyChanged("Capabilities");
            }
        }

        /// <summary>
        /// A human-readable description of the resource.
        /// </summary>
        [JsonProperty("description")]
        public string Description 
        { 
            get 
            {
                return this.description; 
            } 
            set 
            {
                this.description = value;
                onPropertyChanged("Description");
            }
        }

        /// <summary>
        /// Whether or not the resource should have children.
        /// </summary>
        [JsonProperty("hierarchical")]
        public string Hierarchical 
        { 
            get 
            {
                return this.hierarchical; 
            } 
            set 
            {
                this.hierarchical = value;
                onPropertyChanged("Hierarchical");
            }
        }

        /// <summary>
        /// Human-readable labels for the resource for various contexts.
        /// </summary>
        [JsonProperty("labels")]
        public string Labels 
        { 
            get 
            {
                return this.labels; 
            } 
            set 
            {
                this.labels = value;
                onPropertyChanged("Labels");
            }
        }

        /// <summary>
        /// The title for the resource.
        /// </summary>
        [JsonProperty("name")]
        public string Name 
        { 
            get 
            {
                return this.name; 
            } 
            set 
            {
                this.name = value;
                onPropertyChanged("Name");
            }
        }

        /// <summary>
        /// An alphanumeric identifier for the object unique to its type.
        /// </summary>
        [JsonProperty("slug")]
        public string Slug 
        { 
            get 
            {
                return this.slug; 
            } 
            set 
            {
                this.slug = value;
                onPropertyChanged("Slug");
            }
        }

        /// <summary>
        /// Whether or not the term cloud should be displayed.
        /// </summary>
        [JsonProperty("show_cloud")]
        public bool? ShowCloud 
        { 
            get 
            {
                return this.showCloud; 
            } 
            set 
            {
                this.showCloud = value;
                onPropertyChanged("ShowCloud");
            }
        }

        /// <summary>
        /// Types associated with resource.
        /// </summary>
        [JsonProperty("types")]
        public List<string> Types 
        { 
            get 
            {
                return this.types; 
            } 
            set 
            {
                this.types = value;
                onPropertyChanged("Types");
            }
        }
    }
} 