/*
 * WordpressV2API.PCL
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 03/06/2017
 */
using System;
using System.Linq;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using WordpressV2API.PCL;
using WordpressV2API.PCL.Utilities;

namespace WordpressV2API.PCL.Models
{
    [JsonConverter(typeof(StringValuedEnumConverter))]
    public enum Taxonomy6Enum
    {
        ENUM_CATEGORY, //TODO: Write general description for this method
        POST_TAG, //TODO: Write general description for this method
        NAV_MENU, //TODO: Write general description for this method
        LINK_CATEGORY, //TODO: Write general description for this method
        POST_FORMAT, //TODO: Write general description for this method
    }

    /// <summary>
    /// Helper for the enum type Taxonomy6Enum
    /// </summary>
    public static class Taxonomy6EnumHelper
    {
        //string values corresponding the enum elements
        private static List<string> stringValues = new List<string> { "category", "post_tag", "nav_menu", "link_category", "post_format" };

        /// <summary>
        /// Converts a Taxonomy6Enum value to a corresponding string value
        /// </summary>
        /// <param name="enumValue">The Taxonomy6Enum value to convert</param>
        /// <returns>The representative string value</returns>
        public static string ToValue(Taxonomy6Enum enumValue)
        {
            switch(enumValue)
            {
                //only valid enum elements can be used
                //this is necessary to avoid errors
                case Taxonomy6Enum.ENUM_CATEGORY:
                case Taxonomy6Enum.POST_TAG:
                case Taxonomy6Enum.NAV_MENU:
                case Taxonomy6Enum.LINK_CATEGORY:
                case Taxonomy6Enum.POST_FORMAT:
                    return stringValues[(int)enumValue];

                //an invalid enum value was requested
                default:
                    return null;
            }
        }

        /// <summary>
        /// Convert a list of Taxonomy6Enum values to a list of strings
        /// </summary>
        /// <param name="enumValues">The list of Taxonomy6Enum values to convert</param>
        /// <returns>The list of representative string values</returns>
        public static List<string> ToValue(List<Taxonomy6Enum> enumValues)
        {
            if (null == enumValues)
                return null;

            return enumValues.Select(eVal => ToValue(eVal)).ToList();
        }

        /// <summary>
        /// Converts a string value into Taxonomy6Enum value
        /// </summary>
        /// <param name="value">The string value to parse</param>
        /// <returns>The parsed Taxonomy6Enum value</returns>
        public static Taxonomy6Enum ParseString(string value)
        {
            int index = stringValues.IndexOf(value);
            if(index < 0)
                throw new InvalidCastException(string.Format("Unable to cast value: {0} to type Taxonomy6Enum", value));

            return (Taxonomy6Enum) index;
        }
    }
} 