/*
 * WordpressV2API.PCL
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using WordpressV2API.PCL;
using WordpressV2API.PCL.Utilities;

namespace WordpressV2API.PCL.Models
{
    public class User : BaseModel 
    {
        // These fields hold the values for the public properties.
        private int? id;
        private string username;
        private string name;
        private string firstName;
        private string lastName;
        private string email;
        private string url;
        private string description;
        private string link;
        private string nickname;
        private string slug;
        private string registeredDate;
        private List<string> roles;
        private string password;
        private List<string> capabilities;
        private List<string> extraCapabilities;
        private List<string> avatarUrls;

        /// <summary>
        /// Unique identifier for the object.
        /// </summary>
        [JsonProperty("id")]
        public int? Id 
        { 
            get 
            {
                return this.id; 
            } 
            set 
            {
                this.id = value;
                onPropertyChanged("Id");
            }
        }

        /// <summary>
        /// Login name for the resource.
        /// </summary>
        [JsonProperty("username")]
        public string Username 
        { 
            get 
            {
                return this.username; 
            } 
            set 
            {
                this.username = value;
                onPropertyChanged("Username");
            }
        }

        /// <summary>
        /// Display name for the resource.
        /// </summary>
        [JsonProperty("name")]
        public string Name 
        { 
            get 
            {
                return this.name; 
            } 
            set 
            {
                this.name = value;
                onPropertyChanged("Name");
            }
        }

        /// <summary>
        /// First name for the resource.
        /// </summary>
        [JsonProperty("first_name")]
        public string FirstName 
        { 
            get 
            {
                return this.firstName; 
            } 
            set 
            {
                this.firstName = value;
                onPropertyChanged("FirstName");
            }
        }

        /// <summary>
        /// Last name for the resource.
        /// </summary>
        [JsonProperty("last_name")]
        public string LastName 
        { 
            get 
            {
                return this.lastName; 
            } 
            set 
            {
                this.lastName = value;
                onPropertyChanged("LastName");
            }
        }

        /// <summary>
        /// The email address for the resource.
        /// </summary>
        [JsonProperty("email")]
        public string Email 
        { 
            get 
            {
                return this.email; 
            } 
            set 
            {
                this.email = value;
                onPropertyChanged("Email");
            }
        }

        /// <summary>
        /// URL of the resource.
        /// </summary>
        [JsonProperty("url")]
        public string Url 
        { 
            get 
            {
                return this.url; 
            } 
            set 
            {
                this.url = value;
                onPropertyChanged("Url");
            }
        }

        /// <summary>
        /// Description of the resource.
        /// </summary>
        [JsonProperty("description")]
        public string Description 
        { 
            get 
            {
                return this.description; 
            } 
            set 
            {
                this.description = value;
                onPropertyChanged("Description");
            }
        }

        /// <summary>
        /// Author URL to the resource.
        /// </summary>
        [JsonProperty("link")]
        public string Link 
        { 
            get 
            {
                return this.link; 
            } 
            set 
            {
                this.link = value;
                onPropertyChanged("Link");
            }
        }

        /// <summary>
        /// The nickname for the resource.
        /// </summary>
        [JsonProperty("nickname")]
        public string Nickname 
        { 
            get 
            {
                return this.nickname; 
            } 
            set 
            {
                this.nickname = value;
                onPropertyChanged("Nickname");
            }
        }

        /// <summary>
        /// An alphanumeric identifier for the resource.
        /// </summary>
        [JsonProperty("slug")]
        public string Slug 
        { 
            get 
            {
                return this.slug; 
            } 
            set 
            {
                this.slug = value;
                onPropertyChanged("Slug");
            }
        }

        /// <summary>
        /// Registration date for the resource.
        /// </summary>
        [JsonProperty("registered_date")]
        public string RegisteredDate 
        { 
            get 
            {
                return this.registeredDate; 
            } 
            set 
            {
                this.registeredDate = value;
                onPropertyChanged("RegisteredDate");
            }
        }

        /// <summary>
        /// Roles assigned to the resource.
        /// </summary>
        [JsonProperty("roles")]
        public List<string> Roles 
        { 
            get 
            {
                return this.roles; 
            } 
            set 
            {
                this.roles = value;
                onPropertyChanged("Roles");
            }
        }

        /// <summary>
        /// Password for the resource (never included).
        /// </summary>
        [JsonProperty("password")]
        public string Password 
        { 
            get 
            {
                return this.password; 
            } 
            set 
            {
                this.password = value;
                onPropertyChanged("Password");
            }
        }

        /// <summary>
        /// All capabilities assigned to the resource.
        /// </summary>
        [JsonProperty("capabilities")]
        public List<string> Capabilities 
        { 
            get 
            {
                return this.capabilities; 
            } 
            set 
            {
                this.capabilities = value;
                onPropertyChanged("Capabilities");
            }
        }

        /// <summary>
        /// Any extra capabilities assigned to the resource.
        /// </summary>
        [JsonProperty("extra_capabilities")]
        public List<string> ExtraCapabilities 
        { 
            get 
            {
                return this.extraCapabilities; 
            } 
            set 
            {
                this.extraCapabilities = value;
                onPropertyChanged("ExtraCapabilities");
            }
        }

        /// <summary>
        /// Avatar URLs for the resource.
        /// </summary>
        [JsonProperty("avatar_urls")]
        public List<string> AvatarUrls 
        { 
            get 
            {
                return this.avatarUrls; 
            } 
            set 
            {
                this.avatarUrls = value;
                onPropertyChanged("AvatarUrls");
            }
        }
    }
} 